# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TruffleCli < Formula
  desc ""
  homepage "https://github.com/deepshard/truffle-cli"
  version "2.1"
  depends_on :macos

  url "https://github.com/deepshard/truffle-cli/releases/download/v2.1/truffle-cli_Darwin_all.tar.gz"
  sha256 "4939c9fefd82535b1c0b53a3b906c21499ab2c5b3a9b537ccc69bd21f96c06eb"

  def install
    bin.install "truffle-cli"
  end
end
